#pragma once

#include <Mosaic/Mosaic.hpp>

namespace MosaicExample
{
    struct PropertyDemoNode
    {
        size_t parent = std::numeric_limits<size_t>::max();
        uint32_t uid = 0;
        uint32_t depth = 0;
        bool expanded = false;
        bool hasData = false;
        bool enabled = true;
        Mosaic::String name;
        Mosaic::Array<int32_t, 4> integers = {};
        Mosaic::Array<float, 3> scalars = {0.25f, 0.5f, 0.75f};
    };

    using PropertyDemoNodeVector = Mosaic::Vector<PropertyDemoNode>;

    enum class DebugDemoCategory : uint8_t
    {
        Errors,
        ActiveItem,
        Clipper,
        Docking,
        Focus,
        Font,
        Popup,
        Selection,
        Table,
        Viewport,
        Count
    };

    struct DebugDemoEvent
    {
        DebugDemoCategory category = DebugDemoCategory::ActiveItem;
        Mosaic::Id id = Mosaic::InvalidId;
        Mosaic::String text;
    };

    using DebugDemoEventVector = Mosaic::Vector<DebugDemoEvent>;

    class HelloDemo
    {
    public:
        void draw(Mosaic::Context * ui, float deltaTime);
        void setRenderMetrics(const Mosaic::RenderMesh & mesh) noexcept;
        [[nodiscard]] const Mosaic::Color & clearColor() const noexcept;

    private:
        void drawDemoWindow(Mosaic::Context * ui);
        void drawDemoContents(Mosaic::Context * ui);
        void drawHelloWindow(Mosaic::Context * ui);
        void drawAnotherWindow(Mosaic::Context * ui);
        void drawMenuBar(Mosaic::Context * ui);
        void drawExampleMenuFile(Mosaic::Context * ui);
        void drawFontAtlas(Mosaic::Context * ui);
        void drawImageViewerContents(Mosaic::Context * ui);
        void drawHelp(Mosaic::Context * ui);
        void drawConfiguration(Mosaic::Context * ui);
        void drawWindowOptions(Mosaic::Context * ui);
        void drawWidgets(Mosaic::Context * ui);
        void drawLayout(Mosaic::Context * ui);
        void drawPopups(Mosaic::Context * ui);
        void drawTables(Mosaic::Context * ui);
        void drawInputs(Mosaic::Context * ui);
        void drawCustomRendering(Mosaic::Context * ui);
        void drawExampleWindows(Mosaic::Context * ui);
        void drawToolWindows(Mosaic::Context * ui);
        void initializePropertyEditor();
        void appendVisiblePropertyNode(size_t index);
        void drawPropertyNode(Mosaic::Context * ui, size_t index);
        static void consoleInputCallback(Mosaic::TextInputCallbackData & data);
        void executeConsoleCommand(Mosaic::StringView command);
        void addConsoleLog(Mosaic::String value);

    private:
        Mosaic::SelectionModel m_tableSelection{Mosaic::SelectionMode::Multiple};
        Mosaic::SelectionModel m_secondarySelection{Mosaic::SelectionMode::Multiple};
        Mosaic::SelectionModel m_treeSelection{Mosaic::SelectionMode::Multiple};
        Mosaic::SelectionModel m_advancedSelection{Mosaic::SelectionMode::Multiple};
        Mosaic::SelectionModel m_assetSelection{Mosaic::SelectionMode::Multiple};
        Mosaic::SelectionModel m_propertySelection{Mosaic::SelectionMode::Single};
        Mosaic::Array<Mosaic::SelectionModel, 2> m_dualListSelections = {Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}};
        Mosaic::Array<Mosaic::SelectionModel, 3> m_scopeSelections = {Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}};
        Mosaic::Array<Mosaic::SelectionModel, 10> m_selectionModels = {Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}, Mosaic::SelectionModel{Mosaic::SelectionMode::Multiple}};
        Mosaic::Theme m_demoTheme;
        Mosaic::Theme m_timelineThemeBase;
        Mosaic::Array<Mosaic::Theme, 20> m_timelineButtonThemes;
        bool m_timelineThemesInitialized = false;
        Mosaic::String m_singleLine = "Hello, world!";
        Mosaic::String m_liveEditLine = "Hello, world!";
        Mosaic::String m_miscTextLine = "Hello, world!";
        Mosaic::String m_hintInput;
        Mosaic::String m_multiline = "/*\n"
                                     " The Pentium F00F bug, shorthand for F0 0F C7 C8,\n"
                                     " the hexadecimal encoding of one offending instruction,\n"
                                     " more formally, the invalid operand with locked CMPXCHG8B\n"
                                     " instruction bug, is a design flaw in the majority of\n"
                                     " Intel Pentium, Pentium MMX, and Pentium OverDrive\n"
                                     " processors (all in the P5 microarchitecture).\n"
                                     "*/\n\n"
                                     "label:\n"
                                     "\tlock cmpxchg8b eax\n";
        Mosaic::String m_filter;
        Mosaic::TextFilter m_textFilter;
        Mosaic::String m_comboFilter;
        Mosaic::TextFilter m_comboTextFilter;
        Mosaic::String m_password = "password123";
        Mosaic::String m_utf8Input = "日本語";
        Mosaic::String m_filteredDefault;
        Mosaic::String m_filteredDecimal;
        Mosaic::String m_filteredHexadecimal;
        Mosaic::String m_filteredUppercase;
        Mosaic::String m_filteredNoBlank;
        Mosaic::String m_filteredCasingSwap;
        Mosaic::String m_filteredLowercase;
        Mosaic::String m_commandInput;
        Mosaic::String m_completionInput;
        Mosaic::String m_historyInput;
        Mosaic::String m_editCallbackInput;
        Mosaic::String m_resizeInput = "This text buffer grows as you type.";
        Mosaic::String m_elidePath = "/path/to/some/folder/with/long/filename.cpp";
        Mosaic::String m_contextLabel = "Label1";
        Mosaic::String m_consoleFilter;
        Mosaic::String m_logFilter;
        Mosaic::TextFilter m_consoleTextFilter;
        Mosaic::TextFilter m_logTextFilter;
        Mosaic::String m_longTextBuffer;
        Mosaic::String m_propertyFilter;
        Mosaic::String m_queryInput;
        Mosaic::Array<Mosaic::String, 5> m_tabbingInputs;
        Mosaic::Array<Mosaic::String, 3> m_focusInputs;
        Mosaic::StringVector m_consoleItems = {"Welcome to Mosaic!"};
        Mosaic::StringVector m_consoleHistory;
        Mosaic::StringVector m_logItems;
        DebugDemoEventVector m_debugEventItems;
        size_t m_debugEventHead = 0;
        Mosaic::SizeVector m_consoleVisibleItems;
        Mosaic::SizeVector m_logVisibleItems;
        Mosaic::SizeVector m_assetVisibleItems;
        Mosaic::SizeVector m_debugVisibleEvents;
        bool m_debugVisibleEventsDirty = true;
        Mosaic::StringVector m_dragItems = {"Bobby", "Beatrice", "Betty", "Brianna", "Barry", "Bernard", "Bibi", "Blaine", "Bryn"};
        Mosaic::StringVector m_reorderItems = {"Bobby", "Beatrice", "Betty", "Brianna", "Barry", "Bernard", "Bibi", "Blaine", "Bryn"};
        Mosaic::UInt32Vector m_dynamicTabIds = {0, 1, 2};
        Mosaic::FontCacheAction m_pendingFontCacheAction = Mosaic::FontCacheAction::Compact;
        bool m_fontCacheActionPending = false;
        Mosaic::Vec2Vector m_canvasPoints;
        Mosaic::Color m_clearColor = {0.45f, 0.55f, 0.60f, 1.f};
        Mosaic::Color m_color1 = {1.f, 0.f, 0.2f, 1.f};
        Mosaic::Color m_color2 = {0.4f, 0.7f, 0.f, 0.5f};
        Mosaic::Color m_colorReference = {1.f, 0.f, 1.f, 0.5f};
        Mosaic::Color m_colorBackup = m_color2;
        Mosaic::Color m_colorHsv = {0.23f, 1.f, 1.f, 1.f};
        Mosaic::Color m_queryColor = {0.4f, 0.7f, 0.f, 1.f};
        Mosaic::Color m_dragDropColor1 = {1.f, 0.f, 0.2f, 1.f};
        Mosaic::Color m_dragDropColor2 = {0.4f, 0.7f, 0.f, 0.5f};
        Mosaic::Color m_customColor = {1.f, 0.f, 0.2f, 1.f};
        Mosaic::Array<Mosaic::Color, 32> m_colorPalette = {};
        Mosaic::Array<Mosaic::Color, 6> m_documentColors = {{{0.4f, 0.8f, 0.4f, 1.f}, {0.8f, 0.5f, 1.f, 1.f}, {1.f, 0.8f, 0.5f, 1.f}, {1.f, 0.3f, 0.4f, 1.f}, {0.4f, 0.8f, 0.8f, 1.f}, {0.8f, 0.8f, 1.f, 1.f}}};
        Mosaic::Array<float, 4> m_vector = {0.1f, 0.2f, 0.3f, 0.44f};
        Mosaic::Array<int32_t, 4> m_integerVector = {1, 5, 100, 255};
        Mosaic::Array<float, 90> m_plotValues = {};
        Mosaic::Array<float, 7> m_verticalSliders = {0.f, 0.6f, 0.35f, 0.9f, 0.7f, 0.2f, 0.f};
        Mosaic::Array<float, 4> m_verticalSmallSliders = {0.2f, 0.8f, 0.4f, 0.25f};
        int32_t m_verticalInteger = 0;
        Mosaic::Array<bool, 8> m_selectableBasicStates = {false, true, false, false, false, false, false, false};
        Mosaic::Array<bool, 3> m_selectableSameLineStates = {};
        Mosaic::Array<bool, 5> m_selectableSameLineChecks = {};
        Mosaic::Array<bool, 10> m_selectableTableCellStates = {};
        Mosaic::Array<bool, 10> m_selectableTableRowStates = {};
        Mosaic::Array<bool, 16> m_selectableGridStates = {true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true};
        Mosaic::Array<bool, 9> m_selectableAlignmentStates = {};
        Mosaic::Array<bool, 50> m_selectionCheckboxStates = {};
        Mosaic::Array<bool, 6> m_treeSelectableStates = {};
        Mosaic::Array<bool, 6> m_treeAdvancedSelectableStates = {};
        Mosaic::Array<bool, 32> m_configurationFlags = {};
        Mosaic::Array<bool, 5> m_popupToggles = {true, false, false, false, false};
        Mosaic::Array<bool, 4> m_tabOpen = {true, true, true, true};
        Mosaic::Array<bool, 6> m_documentOpen = {true, true, true, false, false, false};
        Mosaic::Array<bool, 6> m_documentDirty = {};
        Mosaic::Array<Mosaic::String, 6> m_documentNames = {"Lettuce", "Eggplant", "Carrot", "Tomato", "A Rather Long Title", "Some Document"};
        Mosaic::Array<bool, 13> m_configurationSecondary = {false, false, false, false, true, false, true, false, false, true, false, false, false};
        Mosaic::Array<bool, 8> m_backendFlags = {true, false, false, false, false, true, true, false};
        Mosaic::Array<bool, 4> m_richTextChecks = {true, false, true, false};
        Mosaic::Array<bool, 6> m_tableAdvancedFlags = {true, false, true, false, false, true};
        Mosaic::Array<bool, 5> m_metricsOverlayFlags = {true, false, true, false, false};
        Mosaic::Array<bool, static_cast<size_t>(DebugDemoCategory::Count)> m_debugLogCategories = {true, true, true, true, true, true, true, true, true, true};
        Mosaic::Array<size_t, 7> m_debugSnapshotCounts = {std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max()};
        Mosaic::Array<float, 120> m_metricsMemoryHistory = {};
        Mosaic::Id m_metricsSelectedNode = Mosaic::InvalidId;
        Mosaic::SizeVector m_metricsNodeIndices;
        Mosaic::Id m_itemPickerTarget = Mosaic::InvalidId;
        uint64_t m_metricsMemoryFrame = 0;
        size_t m_metricsMemoryOffset = 0;
        double m_idStackCopyFeedbackUntil = 0.0;
        Mosaic::String m_metricsEncodingInput = "Mosaic UTF-8: 日本語";
        Mosaic::SizeVector m_advancedTableOrder;
        Mosaic::Vector<int32_t> m_advancedTableQuantities;
        Mosaic::TableSortSpecVector m_tableSortCache;
        Mosaic::IdVector m_tableOrderedIds;
        bool m_advancedTableDataDirty = true;
        Mosaic::IdVector m_advancedSelectionOrder;
        Mosaic::IdVector m_advancedSelectionNodes;
        Mosaic::Array<Mosaic::Id, 15> m_selectionTreeNodeIds = {};
        Mosaic::IdVector m_assetVisibleOrder;
        Mosaic::SizeVector m_documentCloseQueue;
        Mosaic::IdVector m_propertyOrder;
        Mosaic::SizeVector m_assetItems;
        Mosaic::SizeVector m_propertyVisibleNodes;
        PropertyDemoNodeVector m_propertyNodes;
        Mosaic::Array<Mosaic::IdVector, 10> m_selectionOrders;
        Mosaic::Array<Mosaic::IdVector, 2> m_dualListItems;
        size_t m_deletionNextId = 1;
        size_t m_advancedSelectionNextId = 1;
        bool m_deletionInitialized = false;
        bool m_dualListInitialized = false;
        bool m_initialized = false;
        bool m_themeInitialized = false;
        bool m_showDemoWindow = true;
        bool m_showAnotherWindow = false;
        bool m_showCustomRendering = false;
        bool m_showConsole = false;
        bool m_showSimpleLayout = false;
        bool m_showStyleEditor = false;
        bool m_showMainMenuBar = false;
        bool m_showAssetsBrowser = false;
        bool m_showDocuments = false;
        bool m_showDockspace = false;
        bool m_showImageViewer = false;
        bool m_showLog = false;
        bool m_showPropertyEditor = false;
        bool m_showSimpleOverlay = false;
        bool m_showAutoResize = false;
        bool m_showConstrainedResize = false;
        bool m_showFullscreen = false;
        bool m_showLongText = false;
        bool m_showWindowTitles = false;
        bool m_showMetrics = false;
        bool m_showDebugLog = false;
        bool m_showIdStack = false;
        bool m_itemPickerArmed = false;
        bool m_showAbout = false;
        bool m_showHorizontalContentsSizeWindow = false;
        bool m_assetShowTypeOverlay = true;
        bool m_assetAllowSorting = true;
        bool m_assetAllowBoxSelect = true;
        bool m_assetAllowBoxSelectInsideSelection = false;
        bool m_assetAllowDragUnselected = false;
        bool m_assetStretchSpacing = true;
        bool m_assetOrderDirty = true;
        bool m_assetUseScrollX = false;
        bool m_assetZoomScrollPending = false;
        bool m_customEnableGrid = true;
        bool m_customEnableContextMenu = true;
        bool m_customCircleSegmentsOverride = false;
        bool m_customCurveSegmentsOverride = false;
        bool m_customDrawBackground = false;
        bool m_customDrawForeground = false;
        bool m_customAddingLine = false;
        bool m_customCanvasPanning = false;
        bool m_imageViewerPanning = false;
        bool m_imageViewerGrid = true;
        bool m_imageViewerViewReset = true;
        bool m_horizontalShowScrollbar = true;
        bool m_horizontalShowButton = true;
        bool m_horizontalShowTreeNodes = true;
        bool m_horizontalShowTextWrapped = false;
        bool m_horizontalShowColumns = true;
        bool m_horizontalShowTabBar = true;
        bool m_horizontalShowChild = false;
        bool m_horizontalExplicitContentSize = false;
        bool m_overlayOpen = true;
        bool m_logAutoScroll = true;
        bool m_debugLogAutoScroll = true;
        bool m_constrainedAutoResize = false;
        bool m_dockspaceFullscreen = true;
        bool m_dockspaceNoResize = false;
        bool m_dockspaceNoUndocking = false;
        bool m_dockspaceNoDockingOverCentral = false;
        bool m_dockspacePassthruCentral = false;
        bool m_dockspaceAutoHideTabBar = false;
        bool m_dockspaceModeChanged = false;
        bool m_demoCollapsed = false;
        bool m_helloCollapsed = false;
        bool m_anotherCollapsed = false;
        bool m_customCollapsed = false;
        bool m_consoleCollapsed = false;
        bool m_consoleAutoScroll = true;
        bool m_consoleVisibleDirty = true;
        bool m_logVisibleDirty = true;
        uint8_t m_consoleScrollToBottomFrames = 0;
        bool m_layoutCollapsed = false;
        bool m_enabled = true;
        bool m_toggle = true;
        bool m_basicCheckbox = true;
        bool m_disabledSection = false;
        bool m_disabledCheckbox = false;
        bool m_queryCheckbox = false;
        bool m_textEscapeClearsAll = true;
        bool m_textDisableUndoRedo = false;
        bool m_selectionRange = true;
        bool m_selectionBox = false;
        bool m_treeDrawLinesToNodes = false;
        bool m_treeAlignLabel = true;
        bool m_treeDragSource = false;
        bool m_documentsReorderable = true;
        bool m_documentsDockInitialized = false;
        bool m_documentsRedockRequested = false;
        bool m_dockspaceKeepPadding = false;
        bool m_propertyUseClipper = false;
        bool m_constrainedWindowPadding = false;
        bool m_fullscreenUseWorkArea = true;
        bool m_fullscreenNoBackground = false;
        bool m_fullscreenNoDecoration = true;
        bool m_fullscreenNoTitleBar = false;
        bool m_fullscreenNoCollapse = false;
        bool m_fullscreenNoScrollbar = false;
        bool m_fullscreenCollapsed = false;
        bool m_modalOpen = false;
        bool m_modalDontAsk = false;
        bool m_stackedModalFirst = false;
        bool m_stackedModalSecond = false;
        bool m_popupOption = true;
        bool m_navKeyboard = true;
        bool m_navGamepad = false;
        bool m_navSwapGamepadButtons = false;
        bool m_hoverEnabled = true;
        bool m_animationsEnabled = false;
        bool m_noTitleBar = false;
        bool m_noScrollbar = false;
        bool m_noMenu = false;
        bool m_noMove = false;
        bool m_noResize = false;
        bool m_noCollapse = false;
        bool m_noClose = false;
        bool m_noNavigation = false;
        bool m_noBackground = false;
        bool m_noBringToFront = false;
        bool m_noDocking = false;
        bool m_unsavedDocument = false;
        bool m_comboPopupAlignLeft = false;
        bool m_comboNoArrowButton = false;
        bool m_comboNoPreview = false;
        bool m_comboWidthFitPreview = false;
        bool m_comboHeightSmall = false;
        bool m_comboHeightRegular = true;
        bool m_comboHeightLargest = false;
        bool m_colorPaletteInitialized = false;
        bool m_colorNoAlpha = false;
        bool m_colorAlphaOpaque = false;
        bool m_colorAlphaNoBackground = false;
        bool m_colorAlphaPreviewHalf = false;
        bool m_colorNoOptions = false;
        bool m_colorNoDragDrop = false;
        bool m_colorNoMarkers = false;
        bool m_colorHdr = false;
        bool m_colorNoBorder = false;
        bool m_colorNoTooltip = false;
        bool m_colorNoPicker = false;
        bool m_colorNoSmallPreview = false;
        bool m_colorNoLabel = false;
        bool m_colorReferenceEnabled = false;
        bool m_colorPickerAlpha = true;
        bool m_colorPickerNoSidePreview = false;
        bool m_colorPickerNoRotate = false;
        int m_colorPickerMode = 0;
        int m_colorDisplayMode = 0;
        bool m_showSecondHeader = true;
        bool m_dataClamp = false;
        bool m_dataInputSteps = true;
        bool m_dataReadOnly = false;
        bool m_textMiscReadOnly = false;
        bool m_dataParseEmptyReference = false;
        bool m_dataDisplayEmptyReference = false;
        bool m_sliderClampOnInput = false;
        bool m_sliderClampZeroRange = false;
        bool m_sliderLogarithmic = false;
        bool m_sliderNoRound = false;
        bool m_sliderNoInput = false;
        bool m_sliderNoSpeedTweaks = false;
        bool m_sliderWrapAround = false;
        bool m_sliderColorMarkers = false;
        bool m_liveEditOverride = false;
        bool m_liveEditText = true;
        bool m_liveEditScalar = true;
        bool m_multilineReadOnly = false;
        bool m_multilineWordWrap = false;
        bool m_multilineAllowTab = true;
        bool m_multilineControlEnter = false;
        bool m_queryItemDisabled = false;
        bool m_queryWindowChild = false;
        bool m_queryTitleWindow = false;
        bool m_childDisableWheel = false;
        bool m_childDisableMenu = false;
        bool m_childOverrideBackground = true;
        bool m_childBorders = true;
        bool m_childAlwaysPadding = false;
        bool m_childResizeX = true;
        bool m_childResizeY = true;
        bool m_childFrameStyle = false;
        bool m_widthShowIndented = true;
        bool m_scrollDecoration = false;
        bool m_scrollTrack = true;
        bool m_overlapEnabled = true;
        bool m_legacyHorizontalBorders = true;
        bool m_legacyVerticalBorders = true;
        bool m_shortcutRepeat = true;
        bool m_shortcutTooltip = true;
        bool m_shortcutOverActive = false;
        bool m_shortcutOverFocused = false;
        bool m_shortcutUnlessBackground = false;
        bool m_listHighlight = false;
        bool m_plotAnimate = true;
        int32_t m_integer = 0;
        int8_t m_dataS8 = 127;
        uint8_t m_dataU8 = 255;
        int16_t m_dataS16 = 32767;
        uint16_t m_dataU16 = 65535;
        int32_t m_dataS32 = -1;
        uint32_t m_dataU32 = std::numeric_limits<uint32_t>::max();
        int64_t m_dataS64 = -1;
        uint64_t m_dataU64 = std::numeric_limits<uint64_t>::max();
        int32_t m_inputInteger = 123;
        int32_t m_dragInteger = 50;
        int32_t m_dragPercent = 42;
        int32_t m_dragWrap = 128;
        int32_t m_sliderInteger = 0;
        int32_t m_sliderElement = 0;
        int32_t m_repeatCounter = 0;
        int m_radio = 0;
        int m_combo = 0;
        int m_menuCombo = 0;
        int m_layoutCombo = 0;
        int m_modalCombo = 0;
        int m_queryCombo = 0;
        int m_singleSelection = 0;
        int m_popupSelectedFish = -1;
        int m_contextSelected = -1;
        int m_comboSelected = 0;
        int m_comboOneLiner = 0;
        int m_comboArray = -1;
        int m_comboFunction = 0;
        int m_basicListSelection = 1;
        int m_list = 1;
        int m_queryListSelection = 1;
        int m_groupListSelection = 1;
        int m_legacyColumnSelection = 1;
        int m_simpleLayoutSelection = 0;
        int m_listHovered = -1;
        int m_plotFunction = 0;
        int m_dragDropMode = 0;
        size_t m_dragSourceIndex = std::numeric_limits<size_t>::max();
        float m_reorderDragRemainder = 0.f;
        int m_queryItemType = 4;
        int m_captureOverridePointer = -1;
        int m_captureOverrideKeyboard = -1;
        int m_shortcutRoute = 1;
        int m_documentTab = 0;
        int m_overlayCorner = 0;
        int m_resizeType = 6;
        int m_longTextMode = 0;
        size_t m_propertySelectedNode = 0;
        size_t m_logCounter = 0;
        int m_customTab = 0;
        int m_tooltipAlways = 0;
        int m_dockspaceMode = 0;
        int m_documentOutput = 1;
        int m_documentClosePending = -1;
        int m_documentRenamePending = -1;
        int m_documentTabClosed = -1;
        Mosaic::String m_documentRenameValue;
        Mosaic::Id m_documentRenameOwner = Mosaic::InvalidId;
        Mosaic::Rect m_documentRenameAnchor;
        bool m_documentCloseAllPending = false;
        int m_historyCallbackIndex = -1;
        int m_consoleHistoryPosition = -1;
        int32_t m_childLineCount = 3;
        int32_t m_childMaxLines = 10;
        int32_t m_childOffsetX = 0;
        int32_t m_scrollTrackItem = 50;
        int32_t m_scrollLines = 7;
        int32_t m_autoResizeLines = 10;
        int32_t m_constrainedLines = 10;
        int32_t m_legacyColumnCount = 4;
        int32_t m_longTextLines = 0;
        int32_t m_longTextBufferLines = -1;
        int32_t m_consoleCommandCount = 0;
        int32_t m_editCallbackCount = 0;
        int32_t m_resizeCallbackCount = 0;
        int32_t m_assetIconSpacing = 10;
        int32_t m_assetIconHitSpacing = 4;
        int32_t m_selectionItemCount = 1000;
        int32_t m_customNgonSides = 5;
        int32_t m_customCircleSegments = 12;
        int32_t m_customCurveSegments = 8;
        int32_t m_plotSampleCount = 70;
        int m_basicTab = 0;
        int m_closableTab = 0;
        int m_inlineTab = 0;
        int m_objectTab = 0;
        float m_helloFloat = 0.f;
        float m_inputFloat = 0.001f;
        float m_inputScientific = 1.e10f;
        Mosaic::Array<float, 3> m_inputFloat3 = {0.1f, 0.2f, 0.3f};
        float m_basicSliderFloat = 0.123f;
        float m_basicSliderLog = 0.f;
        float m_basicSliderAngle = 0.f;
        float m_dragSmall = 0.0067f;
        float m_dataFloat = 0.123f;
        float m_disabledSliderFloat = 0.5f;
        float m_clampedFloat = 0.f;
        float m_contextValue = 0.5f;
        float m_progressValue = 0.5f;
        float m_progressDirection = 1.f;
        float m_plotPhase = 0.f;
        float m_plotAccumulator = 0.f;
        float m_rangeFloatBegin = 10.f;
        float m_rangeFloatEnd = 90.f;
        float m_widthFloat = 0.5f;
        float m_legacyColumnFloat = 0.5f;
        float m_shortcutFactor = 0.5f;
        float m_drag = 1.f;
        float m_flagDrag = 0.5f;
        float m_flagSlider = 0.5f;
        Mosaic::Array<float, 4> m_flagDrag4 = {};
        Mosaic::Array<float, 4> m_flagSlider4 = {};
        int32_t m_flagDragInt = 50;
        int32_t m_flagSliderInt = 50;
        size_t m_imagePressedCount = 0;
        size_t m_assetCount = 10000;
        size_t m_assetNextSerial = 1;
        double m_double = 999999.00000001;
        double m_dataDouble = 90000.0123456789;
        float m_splitRatio = 0.30f;
        float m_propertySplitRatio = 0.70f;
        float m_scrollOffsetRequest = 0.f;
        float m_scrollPositionRequest = 200.f;
        float m_imageViewerZoom = 10.f;
        Mosaic::Vec2 m_imageViewerPan;
        Mosaic::Vec2 m_imageViewerPanStart;
        Mosaic::Vec2 m_customCanvasPan;
        Mosaic::Vec2 m_customCanvasPanStart;
        float m_assetIconSize = 40.f;
        float m_assetZoomWheelAccumulator = 0.f;
        Mosaic::Vec2 m_assetZoomScrollTarget;
        Mosaic::Color m_propertyTint = {0.4f, 0.7f, 0.f, 0.5f};
        Mosaic::Color m_modalColor = {0.4f, 0.7f, 0.f, 0.5f};
        float m_customPrimitiveSize = 36.f;
        float m_customThickness = 3.f;
        float m_horizontalContentsSize = 300.f;
        float m_wrapWidth = 200.f;
        float m_constrainedAspect = 16.f / 9.f;
        float m_constrainedStep = 100.f;
        float m_styleAlpha = 1.f;
        float m_styleFontSize = 13.f;
        Mosaic::Theme m_styleReference;
        Mosaic::String m_styleColorFilter;
        Mosaic::FontInfoVector m_availableFonts;
        Mosaic::StringViewVector m_availableFontNames;
        int m_fontPreviewSelection = 0;
        size_t m_fontHoveredRect = std::numeric_limits<size_t>::max();
        bool m_showFontAtlasPreview = true;
        int m_styleAlphaMode = 1;
        bool m_styleReferenceInitialized = false;
        float m_deltaTime = 1.f / 60.f;
        Mosaic::RenderMeshMetrics m_renderMetrics;
        const Mosaic::RenderMesh * m_renderMesh = nullptr;
        size_t m_renderVertexCount = 0;
        size_t m_renderIndexCount = 0;
        size_t m_renderBatchCount = 0;
        size_t m_basicButtonClicks = 0;
        size_t m_helloButtonClicks = 0;
        size_t m_plotOffset = 0;
        uint32_t m_nextDynamicTabId = 3;
        int32_t m_rangeIntBegin = 100;
        int32_t m_rangeIntEnd = 1000;
    };
} // namespace MosaicExample
