add_executable(MosaicCoreTests CoreTests.cpp)
target_link_libraries(MosaicCoreTests PRIVATE Mosaic::Mosaic)
target_include_directories(MosaicCoreTests PRIVATE ${PROJECT_SOURCE_DIR}/src)
mosaic_target_warnings(MosaicCoreTests)
add_test(NAME MosaicCoreTests COMMAND MosaicCoreTests)

add_executable(MosaicNativeSurfaceTests NativeSurfaceTests.cpp)
target_link_libraries(MosaicNativeSurfaceTests PRIVATE Mosaic::Mosaic)
mosaic_target_warnings(MosaicNativeSurfaceTests)
add_test(NAME MosaicNativeSurfaceTests COMMAND MosaicNativeSurfaceTests)
